version: "3.8"
services:
  be:
    container_name: be-container
    restart: always
    build: ./server
    ports:
      - 4000:4000
    depends_on:
      - mongo
  client:
    container_name: fe-container
    restart: always
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - be
  mongo:
    container_name: mongo-backend
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - apiDB:/data/db
volumes:
  apiDB:
