version: "3.8"
services:
  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - my_data:/data/db
  frontend:
    build: ./client
    container_name: frontend_c
    ports:
      - "3000:3000"
    stdin_open: true
  backend:
    build: ./server
    container_name: backend_c
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - ./app/node_modules
    depends_on:
      - database
volumes:
  my_data:
