version: "3"
services:
  api:
    build: ./server
    container_name: api_c
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - ./app/node_modules
    depends_on:
      - mongo
  frontend:
    build: ./client
    container_name: clinet_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-stack
    volumes:
      - mongo-data:/data/db
networks:
  mern-stack:
    driver: bridge
volumes:
  mongo-data:
    driver: local
